from __future__ import annotations

import numpy as np

from pso.operators._numba_kernels import apv_full_iteration, build_trans_pairs


def _normalize_tour(path: list[int]) -> list[int]:
    """Rotate tour so city 0 is at position 0 (canonical representation)."""
    idx = path.index(0)
    if idx == 0:
        return path.copy()
    return path[idx:] + path[:idx]


class APVOperatorsMixin:
    """Adaptive Probability Vector (APV) velocity update operator for TSP-PSO.

    Replaces OX+swap with a per-particle probability vector over all (j, k)
    transpositions (position 0 fixed).  Each iteration the velocity is updated:

        v_i(t+1) = clip(ω·v_i(t) + c_p·r1·P_p(i,t) + c_g·r2·P_g(i,t), 0, 1)

    where P_p / P_g are the transposition occurrence vectors for pbest / gbest.
    The new position is generated by applying each transposition stochastically.

    All tours are normalised to start from city 0 so positional comparisons
    across particles are meaningful.

    The inner loop is JIT-compiled with Numba (parallel over particles).
    First call triggers compilation (a few seconds); subsequent runs use the
    on-disk cache in __pycache__.

    Reference: Mastalerczyk et al., "New update operators for discrete problems
    in Particle Swarm Optimisation", JOCS 2026.

    Algorithm name token: ``"APV"`` (case-insensitive).
    Examples: ``"PSO-APV"``, ``"PSO-APV-Ring"``.

    Args:
        omega: Inertia weight (default 0.5).
        c_p: Personal acceleration constant (default 0.5).
        c_g: Global/social acceleration constant (default 0.5).
    """

    def __init__(
        self, *, omega: float = 0.5, c_p: float = 0.5, c_g: float = 0.5, **kwargs
    ) -> None:
        super().__init__(**kwargs)
        self._omega = omega
        self._c_p = c_p
        self._c_g = c_g

        # Normalise all particles to start from city 0 so position-based
        # transposition comparisons are consistent across particles.
        self.particles = [_normalize_tour(p) for p in self.particles]
        self.global_best = _normalize_tour(self.global_best)
        self.best_path = _normalize_tour(self.best_path)

        n = self.num_city
        N = self.num_particles
        num_trans = (n - 1) * (n - 2) // 2

        self._particles_np: np.ndarray = np.array(self.particles, dtype=np.int64)
        self._pbests_np: np.ndarray = self._particles_np.copy()
        self._pbest_lengths_np: np.ndarray = np.array(self.lengths, dtype=np.float64)
        # Dense velocity: shape (N, num_trans), row i = probability vector for particle i.
        self._velocities_np: np.ndarray = np.zeros((N, num_trans), dtype=np.float64)
        # Precomputed (j, k) pairs in canonical order, shape (num_trans, 2).
        self._pairs: np.ndarray = build_trans_pairs(n)

    # ------------------------------------------------------------------
    # Iteration hook — overridden by SWUOperatorsMixin
    # ------------------------------------------------------------------

    def _run_iteration(
        self,
        particles_np: np.ndarray,
        pbests_np: np.ndarray,
        gbests_np: np.ndarray,
        velocities_np: np.ndarray,
        pbest_lengths_np: np.ndarray,
        dis_mat: np.ndarray,
        n: int,
        num_particles: int,
    ) -> tuple[np.ndarray, np.ndarray]:
        return apv_full_iteration(
            particles_np, pbests_np, gbests_np, velocities_np, pbest_lengths_np,
            self._pairs, self._omega, self._c_p, self._c_g, dis_mat, n, num_particles,
        )

    # ------------------------------------------------------------------
    # Main loop
    # ------------------------------------------------------------------

    def run(self) -> "RunResult":  # type: ignore[override]
        """APV/SWU main loop with Numba-accelerated particle updates.

        Per iteration:
          1. Python: compute gbest for each particle (topology hook).
          2. Numba: velocity update + position update for all particles (parallel).
          3. Python: sync list representation, update global best tracker.
        """
        from experiments.result import RunResult

        n = self.num_city
        N = self.num_particles
        dis_mat = self.dis_mat

        recorded: list[float] = [self.best_length]
        iterations_run = 0

        for cnt in range(1, self.max_iter):
            iterations_run = cnt

            if (
                self.stagnation_window is not None
                and len(recorded) > 130
                and all(v == recorded[-1] for v in recorded[-self.stagnation_window :])
            ):
                break

            # Build gbest array for all particles (topology-dependent, Python).
            gbests_np = np.array(
                [self.get_neighbourhood_best(i) for i in range(N)], dtype=np.int64
            )

            # Numba kernel: updates velocities, pbests, pbest_lengths in-place;
            # returns new particles and their lengths.
            self._particles_np, new_lengths = self._run_iteration(
                self._particles_np, self._pbests_np, gbests_np,
                self._velocities_np, self._pbest_lengths_np, dis_mat, n, N,
            )

            self.lengths = new_lengths.tolist()

            # Sync list representation so topology hooks read current positions.
            for i in range(N):
                self.particles[i] = self._particles_np[i].tolist()

            # Update global best from swarm.
            self._update_global_best()
            if self.global_best_length < self.best_length:
                self.best_length = self.global_best_length
                self.best_path = self.global_best.copy()

            # Also check current-iteration particles directly.
            min_idx = int(np.argmin(new_lengths))
            if new_lengths[min_idx] < self.best_length:
                self.best_length = float(new_lengths[min_idx])
                self.best_path = self._particles_np[min_idx].tolist()

            if cnt % 20 == 0:
                recorded.append(self.best_length)

        return RunResult(
            run_index=0,
            best_path_length=self.best_length,
            best_path=self.best_path.copy(),
            iteration_history=recorded,
            iterations_run=iterations_run,
            wall_time_seconds=0.0,
        )
